const path = require('path');

const obj = {
  development: {
    h1bData: function h1bData(year) {
      const dir = 'data';
      return path.join(dir, `h1b-${year}.xlsx`);
    },
    h1bDataWrite: function h1bDataWrite(year) {
      const dir = 'data';
      return path.join(dir, `h1b-${year}.json`);
    },
    h1bDateHeaderWithTypes: function h1bDateHeaderWithTypes(year) {
      const related2014 = {
        lca_case_number: 'string',
        status: 'string',
        lca_case_submit: 'date',
        decision_date: 'date',
        visa_class: 'string',
        lca_case_employment_start_date: 'date',
        lca_case_employment_end_date: 'date',
        lca_case_employer_name: 'string',
        lca_case_employer_address: 'string',
        lca_case_employer_city: 'string',
        lca_case_employer_state: 'string',
        lca_case_employer_postal_code: 'string',
        lca_case_soc_code: 'string',
        lca_case_soc_name: 'string',
        lca_case_job_title: 'string',
        lca_case_wage_rate_from: 'usd',
        lca_case_wage_rate_to: 'usd',
        lca_case_wage_rate_unit: 'string',
        full_time_pos: 'string',
        total_workers: 'integer',
        lca_case_workloc1_city: 'string',
        lca_case_workloc1_state: 'string',
        pw_1: 'usd',
        pw_unit_1: 'string',
        pw_source_1: 'string',
        other_wage_source_1: 'string',
        yr_source_pub_1: 'integer',
        lca_case_workloc2_city: 'string',
        lca_case_workloc2_state: 'string',
        pw_2: 'usd',
        pw_unit_2: 'string',
        pw_source_2: 'string',
        other_wage_source_2: 'string',
        yr_source_pub_2: 'string',
        lca_case_naics_code: 'integer'
      };

      const obj = {
        '2014-p': related2014,
        '2014': related2014,
        '2015': {
          case_number: 'string',
          case_status: 'string',
          case_submitted: 'date',
          decision_date: 'date',
          visa_class: 'string',
          employment_start_date: 'datestring',
          employment_end_date: 'datestring',
          employer_name: 'string',
          employer_address1: 'string',
          employer_address2: 'string',
          employer_city: 'string',
          employer_state: 'string',
          employer_postal_code: 'string',
          employer_country: 'string',
          employer_province: 'string',
          employer_phone: 'integer',
          employer_phone_ext: 'integer',
          agent_attorney_name: 'string',
          agent_attorney_city: 'string',
          agent_attorney_state: 'string',
          job_title: 'string',
          soc_code: 'string',
          soc_name: 'string',
          naic_code: 'integer',
          total_workers: 'integer',
          full_time_position: 'string',
          prevailing_wage: 'usd',
          pw_unit_of_pay: 'string',
          pw_wage_level: 'string',
          pw_wage_source: 'string',
          pw_wage_source_year: 'integer',
          pw_wage_source_other: 'string',
          wage_rate_of_pay: 'usdrange',
          wage_rate_of_pay_from: 'usd',
          wage_rate_of_pay_to: 'usd',
          'h-1b_dependent': 'string',
          willful_violator: 'string',
          worksite_city: 'string',
          worksite_county: 'string',
          worksite_state: 'string',
          worksite_postal_code: 'string'
        },
        '2016': {
          case_number: 'string',
          case_status: 'string',
          case_submitted: 'date',
          decision_date: 'date',
          visa_class: 'string',
          employment_start_date: 'date',
          employment_end_date: 'date',
          employer_name: 'string',
          employer_address: 'string',
          employer_city: 'string',
          employer_state: 'string',
          employer_postal_code: 'string',
          employer_country: 'string',
          employer_province: 'string',
          employer_phone: 'integer',
          employer_phone_ext: 'integer',
          agent_attorney_name: 'string',
          agent_attorney_city: 'string',
          agent_attorney_state: 'string',
          job_title: 'string',
          soc_code: 'string',
          soc_name: 'string',
          naic_code: 'integer',
          total_workers: 'integer',
          full_time_position: 'string',
          prevailing_wage: 'usd',
          pw_unit_of_pay: 'string',
          pw_wage_source: 'string',
          pw_source_year: 'integer',
          pw_source_other: 'string',
          wage_rate_of_pay_from: 'usd',
          wage_rate_of_pay_to: 'usd',
          wage_unit_of_pay: 'string',
          'h-1b_dependent': 'string',
          willful_violator: 'string',
          worksite_city: 'string',
          worksite_county: 'string',
          worksite_state: 'string',
          worksite_postal_code: 'string',
          original_cert_date: 'date'
        },
        '2017': {
          case_number: 'string',
          case_status: 'string',
          case_submitted: 'date',
          decision_date: 'date',
          visa_class: 'string',
          employment_start_date: 'date',
          employment_end_date: 'date',
          employer_name: 'string',
          employer_business_dba: 'string',
          employer_address: 'string',
          employer_city: 'string',
          employer_state: 'string',
          employer_postal_code: 'string',
          employer_country: 'string',
          employer_province: 'string',
          employer_phone: 'integer',
          employer_phone_ext: 'integer',
          agent_representing_employer: 'string',
          agent_attorney_name: 'string',
          agent_attorney_city: 'string',
          agent_attorney_state: 'string',
          job_title: 'string',
          soc_code: 'string',
          soc_name: 'string',
          naics_code: 'integer',
          total_workers: 'integer',
          new_employment: 'integer',
          continued_employment: 'integer',
          change_previous_employment: 'integer',
          new_concurrent_employment: 'integer',
          change_employer: 'integer',
          amended_petition: 'integer',
          full_time_position: 'string',
          prevailing_wage: 'usd',
          pw_unit_of_pay: 'string',
          pw_wage_level: 'string',
          pw_source: 'string',
          pw_source_year: 'integer',
          pw_source_other: 'string',
          wage_rate_of_pay_from: 'usd',
          wage_rate_of_pay_to: 'usd',
          wage_unit_of_pay: 'string',
          h1b_dependent: 'string',
          willful_violator: 'string',
          support_h1b: 'string',
          labor_con_agree: 'string',
          public_disclosure_location: 'string',
          worksite_city: 'string',
          worksite_county: 'string',
          worksite_state: 'string',
          worksite_postal_code: 'string',
          original_cert_date: 'date'
        },
        '2018': {
          case_number: 'string',
          case_status: 'string',
          case_submitted: 'date',
          decision_date: 'date',
          visa_class: 'string',
          employment_start_date: 'date',
          employment_end_date: 'date',
          employer_name: 'string',
          employer_business_dba: 'string',
          employer_address: 'string',
          employer_city: 'string',
          employer_state: 'string',
          employer_postal_code: 'string',
          employer_country: 'string',
          employer_province: 'string',
          employer_phone: 'integer',
          employer_phone_ext: 'integer',
          agent_representing_employer: 'string',
          agent_attorney_name: 'string',
          agent_attorney_city: 'string',
          agent_attorney_state: 'string',
          job_title: 'string',
          soc_code: 'string',
          soc_name: 'string',
          naics_code: 'integer',
          total_workers: 'integer',
          new_employment: 'integer',
          continued_employment: 'integer',
          change_previous_employment: 'integer',
          new_concurrent_emp: 'integer',
          change_employer: 'integer',
          amended_petition: 'integer',
          full_time_position: 'string',
          prevailing_wage: 'usd',
          pw_unit_of_pay: 'string',
          pw_wage_level: 'string',
          pw_source: 'string',
          pw_source_year: 'integer',
          pw_source_other: 'string',
          wage_rate_of_pay_from: 'usd',
          wage_rate_of_pay_to: 'usd',
          wage_unit_of_pay: 'string',
          h1b_dependent: 'string',
          willful_violator: 'string',
          support_h1b: 'string',
          labor_con_agree: 'string',
          public_disclosure_location: 'string',
          worksite_city: 'string',
          worksite_county: 'string',
          worksite_state: 'string',
          worksite_postal_code: 'string',
          original_cert_date: 'date'
        }
      };

      return obj[year];
    },
    h1bDataHeaders: function h1bDataHeaders(year) {
      const toStr = new String(year);

      switch (toStr) {
        case '2014':
          return [
            'LCA_CASE_NUMBER',
            'STATUS',
            'LCA_CASE_SUBMIT',
            'DECISION_DATE',
            'VISA_CLASS',
            'LCA_CASE_EMPLOYMENT_START_DATE',
            'LCA_CASE_EMPLOYMENT_END_DATE',
            'LCA_CASE_EMPLOYER_NAME',
            'LCA_CASE_EMPLOYER_ADDRESS',
            'LCA_CASE_EMPLOYER_CITY',
            'LCA_CASE_EMPLOYER_STATE',
            'LCA_CASE_EMPLOYER_POSTAL_CODE',
            'LCA_CASE_SOC_CODE',
            'LCA_CASE_SOC_NAME',
            'LCA_CASE_JOB_TITLE',
            'LCA_CASE_WAGE_RATE_FROM',
            'LCA_CASE_WAGE_RATE_TO',
            'LCA_CASE_WAGE_RATE_UNIT',
            'FULL_TIME_POS',
            'TOTAL_WORKERS',
            'LCA_CASE_WORKLOC1_CITY',
            'LCA_CASE_WORKLOC1_STATE',
            'PW_1',
            'PW_UNIT_1',
            'PW_SOURCE_1',
            'OTHER_WAGE_SOURCE_1',
            'YR_SOURCE_PUB_1',
            'LCA_CASE_WORKLOC2_CITY',
            'LCA_CASE_WORKLOC2_STATE',
            'PW_2',
            'PW_UNIT_2',
            'PW_SOURCE_2',
            'OTHER_WAGE_SOURCE_2',
            'YR_SOURCE_PUB_2',
            'LCA_CASE_NAICS_CODE'
          ];
        case '2015':
          return [
            'CASE_NUMBER',
            'CASE_STATUS',
            'CASE_SUBMITTED',
            'DECISION_DATE',
            'VISA_CLASS',
            'EMPLOYMENT_START_DATE',
            'EMPLOYMENT_END_DATE',
            'EMPLOYER_NAME',
            'EMPLOYER_ADDRESS1',
            'EMPLOYER_ADDRESS2',
            'EMPLOYER_CITY',
            'EMPLOYER_STATE',
            'EMPLOYER_POSTAL_CODE',
            'EMPLOYER_COUNTRY',
            'EMPLOYER_PROVINCE',
            'EMPLOYER_PHONE',
            'EMPLOYER_PHONE_EXT',
            'AGENT_ATTORNEY_NAME',
            'AGENT_ATTORNEY_CITY',
            'AGENT_ATTORNEY_STATE',
            'JOB_TITLE',
            'SOC_CODE',
            'SOC_NAME',
            'NAIC_CODE',
            'TOTAL WORKERS',
            'FULL_TIME_POSITION',
            'PREVAILING_WAGE',
            'PW_UNIT_OF_PAY',
            'PW_WAGE_LEVEL',
            'PW_WAGE_SOURCE',
            'PW_WAGE_SOURCE_YEAR',
            'PW_WAGE_SOURCE_OTHER',
            'WAGE_RATE_OF_PAY',
            'WAGE_UNIT_OF_PAY',
            'H-1B_DEPENDENT',
            'WILLFUL VIOLATOR',
            'WORKSITE_CITY',
            'WORKSITE_COUNTY',
            'WORKSITE_STATE',
            'WORKSITE_POSTAL_CODE'
          ];
        case '2016':
          return [
            'CASE_NUMBER',
            'CASE_STATUS',
            'CASE_SUBMITTED',
            'DECISION_DATE',
            'VISA_CLASS',
            'EMPLOYMENT_START_DATE',
            'EMPLOYMENT_END_DATE',
            'EMPLOYER_NAME',
            'EMPLOYER_ADDRESS',
            'EMPLOYER_CITY',
            'EMPLOYER_STATE',
            'EMPLOYER_POSTAL_CODE',
            'EMPLOYER_COUNTRY',
            'EMPLOYER_PROVINCE',
            'EMPLOYER_PHONE',
            'EMPLOYER_PHONE_EXT',
            'AGENT_ATTORNEY_NAME',
            'AGENT_ATTORNEY_CITY',
            'AGENT_ATTORNEY_STATE',
            'JOB_TITLE',
            'SOC_CODE',
            'SOC_NAME',
            'NAIC_CODE',
            'TOTAL_WORKERS',
            'FULL_TIME_POSITION',
            'PREVAILING_WAGE',
            'PW_UNIT_OF_PAY',
            'PW_WAGE_SOURCE',
            'PW_SOURCE_YEAR',
            'PW_SOURCE_OTHER',
            'WAGE_RATE_OF_PAY_FROM',
            'WAGE_RATE_OF_PAY_TO',
            'WAGE_UNIT_OF_PAY',
            'H-1B_DEPENDENT',
            'WILLFUL_VIOLATOR',
            'WORKSITE_CITY',
            'WORKSITE_COUNTY',
            'WORKSITE_STATE',
            'WORKSITE_POSTAL_CODE',
            'ORIGINAL_CERT_DATE'
          ];
        case '2017':
          return [
            'CASE_NUMBER',
            'CASE_STATUS',
            'CASE_SUBMITTED',
            'DECISION_DATE',
            'VISA_CLASS',
            'EMPLOYMENT_START_DATE',
            'EMPLOYMENT_END_DATE',
            'EMPLOYER_NAME',
            'EMPLOYER_BUSINESS_DBA',
            'EMPLOYER_ADDRESS',
            'EMPLOYER_CITY',
            'EMPLOYER_STATE',
            'EMPLOYER_POSTAL_CODE',
            'EMPLOYER_COUNTRY',
            'EMPLOYER_PROVINCE',
            'EMPLOYER_PHONE',
            'EMPLOYER_PHONE_EXT',
            'AGENT_REPRESENTING_EMPLOYER',
            'AGENT_ATTORNEY_NAME',
            'AGENT_ATTORNEY_CITY',
            'AGENT_ATTORNEY_STATE',
            'JOB_TITLE',
            'SOC_CODE',
            'SOC_NAME',
            'NAICS_CODE',
            'TOTAL_WORKERS',
            'NEW_EMPLOYMENT',
            'CONTINUED_EMPLOYMENT',
            'CHANGE_PREVIOUS_EMPLOYMENT',
            'NEW_CONCURRENT_EMPLOYMENT',
            'CHANGE_EMPLOYER',
            'AMENDED_PETITION',
            'FULL_TIME_POSITION',
            'PREVAILING_WAGE',
            'PW_UNIT_OF_PAY',
            'PW_WAGE_LEVEL',
            'PW_SOURCE',
            'PW_SOURCE_YEAR',
            'PW_SOURCE_OTHER',
            'WAGE_RATE_OF_PAY_FROM',
            'WAGE_RATE_OF_PAY_TO',
            'WAGE_UNIT_OF_PAY',
            'H1B_DEPENDENT',
            'WILLFUL_VIOLATOR',
            'SUPPORT_H1B',
            'LABOR_CON_AGREE',
            'PUBLIC_DISCLOSURE_LOCATION',
            'WORKSITE_CITY',
            'WORKSITE_COUNTY',
            'WORKSITE_STATE',
            'WORKSITE_POSTAL_CODE',
            'ORIGINAL_CERT_DATE'
          ];
        case '2018':
          return [
            'CASE_NUMBER',
            'CASE_STATUS',
            'CASE_SUBMITTED',
            'DECISION_DATE',
            'VISA_CLASS',
            'EMPLOYMENT_START_DATE',
            'EMPLOYMENT_END_DATE',
            'EMPLOYER_NAME',
            'EMPLOYER_BUSINESS_DBA',
            'EMPLOYER_ADDRESS',
            'EMPLOYER_CITY',
            'EMPLOYER_STATE',
            'EMPLOYER_POSTAL_CODE',
            'EMPLOYER_COUNTRY',
            'EMPLOYER_PROVINCE',
            'EMPLOYER_PHONE',
            'EMPLOYER_PHONE_EXT',
            'AGENT_REPRESENTING_EMPLOYER',
            'AGENT_ATTORNEY_NAME',
            'AGENT_ATTORNEY_CITY',
            'AGENT_ATTORNEY_STATE',
            'JOB_TITLE',
            'SOC_CODE',
            'SOC_NAME',
            'NAICS_CODE',
            'TOTAL_WORKERS',
            'NEW_EMPLOYMENT',
            'CONTINUED_EMPLOYMENT',
            'CHANGE_PREVIOUS_EMPLOYMENT',
            'NEW_CONCURRENT_EMP',
            'CHANGE_EMPLOYER',
            'AMENDED_PETITION',
            'FULL_TIME_POSITION',
            'PREVAILING_WAGE',
            'PW_UNIT_OF_PAY',
            'PW_WAGE_LEVEL',
            'PW_SOURCE',
            'PW_SOURCE_YEAR',
            'PW_SOURCE_OTHER',
            'WAGE_RATE_OF_PAY_FROM',
            'WAGE_RATE_OF_PAY_TO',
            'WAGE_UNIT_OF_PAY',
            'H1B_DEPENDENT',
            'WILLFUL_VIOLATOR',
            'SUPPORT_H1B',
            'LABOR_CON_AGREE',
            'PUBLIC_DISCLOSURE_LOCATION',
            'WORKSITE_CITY',
            'WORKSITE_COUNTY',
            'WORKSITE_STATE',
            'WORKSITE_POSTAL_CODE',
            'ORIGINAL_CERT_DATE'
          ];
        case '2014-p':
          return [
            'LCA_CASE_NUMBER',
            'STATUS',
            'LCA_CASE_SUBMIT',
            'DECISION_DATE',
            'VISA_CLASS',
            'LCA_CASE_EMPLOYMENT_START_DATE',
            'LCA_CASE_EMPLOYMENT_END_DATE',
            'LCA_CASE_EMPLOYER_NAME',
            'LCA_CASE_EMPLOYER_ADDRESS',
            'LCA_CASE_EMPLOYER_CITY',
            'LCA_CASE_EMPLOYER_STATE',
            'LCA_CASE_EMPLOYER_POSTAL_CODE',
            'LCA_CASE_SOC_CODE',
            'LCA_CASE_SOC_NAME',
            'LCA_CASE_JOB_TITLE',
            'LCA_CASE_WAGE_RATE_FROM',
            'LCA_CASE_WAGE_RATE_TO',
            'LCA_CASE_WAGE_RATE_UNIT',
            'FULL_TIME_POS',
            'TOTAL_WORKERS',
            'LCA_CASE_WORKLOC1_CITY',
            'LCA_CASE_WORKLOC1_STATE',
            'PW_1',
            'PW_UNIT_1',
            'PW_SOURCE_1',
            'OTHER_WAGE_SOURCE_1',
            'YR_SOURCE_PUB_1',
            'LCA_CASE_WORKLOC2_CITY',
            'LCA_CASE_WORKLOC2_STATE',
            'PW_2',
            'PW_UNIT_2',
            'PW_SOURCE_2',
            'OTHER_WAGE_SOURCE_2',
            'YR_SOURCE_PUB_2',
            'LCA_CASE_NAICS_CODE'
          ];
      }
    }
  },
  production: {
    h1bData: function h1bData(year) {
      const dir = 'data';
      return path.join(dir, `h1b-${year}.xlsx`);
    },
    h1bDataHeaders: function h1bDataHeaders(year) {
      const toStr = new String(year);

      switch (toStr) {
        case '2014':
          return [
            'LCA_CASE_NUMBER',
            'STATUS',
            'LCA_CASE_SUBMIT',
            'DECISION_DATE',
            'VISA_CLASS',
            'LCA_CASE_EMPLOYMENT_START_DATE',
            'LCA_CASE_EMPLOYMENT_END_DATE',
            'LCA_CASE_EMPLOYER_NAME',
            'LCA_CASE_EMPLOYER_ADDRESS',
            'LCA_CASE_EMPLOYER_CITY',
            'LCA_CASE_EMPLOYER_STATE',
            'LCA_CASE_EMPLOYER_POSTAL_CODE',
            'LCA_CASE_SOC_CODE',
            'LCA_CASE_SOC_NAME',
            'LCA_CASE_JOB_TITLE',
            'LCA_CASE_WAGE_RATE_FROM',
            'LCA_CASE_WAGE_RATE_TO',
            'LCA_CASE_WAGE_RATE_UNIT',
            'FULL_TIME_POS',
            'TOTAL_WORKERS',
            'LCA_CASE_WORKLOC1_CITY',
            'LCA_CASE_WORKLOC1_STATE',
            'PW_1',
            'PW_UNIT_1',
            'PW_SOURCE_1',
            'OTHER_WAGE_SOURCE_1',
            'YR_SOURCE_PUB_1',
            'LCA_CASE_WORKLOC2_CITY',
            'LCA_CASE_WORKLOC2_STATE',
            'PW_2',
            'PW_UNIT_2',
            'PW_SOURCE_2',
            'OTHER_WAGE_SOURCE_2',
            'YR_SOURCE_PUB_2',
            'LCA_CASE_NAICS_CODE'
          ];
        case '2015':
          return [
            'CASE_NUMBER',
            'CASE_STATUS',
            'CASE_SUBMITTED',
            'DECISION_DATE',
            'VISA_CLASS',
            'EMPLOYMENT_START_DATE',
            'EMPLOYMENT_END_DATE',
            'EMPLOYER_NAME',
            'EMPLOYER_ADDRESS1',
            'EMPLOYER_ADDRESS2',
            'EMPLOYER_CITY',
            'EMPLOYER_STATE',
            'EMPLOYER_POSTAL_CODE',
            'EMPLOYER_COUNTRY',
            'EMPLOYER_PROVINCE',
            'EMPLOYER_PHONE',
            'EMPLOYER_PHONE_EXT',
            'AGENT_ATTORNEY_NAME',
            'AGENT_ATTORNEY_CITY',
            'AGENT_ATTORNEY_STATE',
            'JOB_TITLE',
            'SOC_CODE',
            'SOC_NAME',
            'NAIC_CODE',
            'TOTAL WORKERS',
            'FULL_TIME_POSITION',
            'PREVAILING_WAGE',
            'PW_UNIT_OF_PAY',
            'PW_WAGE_LEVEL',
            'PW_WAGE_SOURCE',
            'PW_WAGE_SOURCE_YEAR',
            'PW_WAGE_SOURCE_OTHER',
            'WAGE_RATE_OF_PAY',
            'WAGE_UNIT_OF_PAY',
            'H-1B_DEPENDENT',
            'WILLFUL VIOLATOR',
            'WORKSITE_CITY',
            'WORKSITE_COUNTY',
            'WORKSITE_STATE',
            'WORKSITE_POSTAL_CODE'
          ];
        case '2016':
          return [
            'CASE_NUMBER',
            'CASE_STATUS',
            'CASE_SUBMITTED',
            'DECISION_DATE',
            'VISA_CLASS',
            'EMPLOYMENT_START_DATE',
            'EMPLOYMENT_END_DATE',
            'EMPLOYER_NAME',
            'EMPLOYER_ADDRESS',
            'EMPLOYER_CITY',
            'EMPLOYER_STATE',
            'EMPLOYER_POSTAL_CODE',
            'EMPLOYER_COUNTRY',
            'EMPLOYER_PROVINCE',
            'EMPLOYER_PHONE',
            'EMPLOYER_PHONE_EXT',
            'AGENT_ATTORNEY_NAME',
            'AGENT_ATTORNEY_CITY',
            'AGENT_ATTORNEY_STATE',
            'JOB_TITLE',
            'SOC_CODE',
            'SOC_NAME',
            'NAIC_CODE',
            'TOTAL_WORKERS',
            'FULL_TIME_POSITION',
            'PREVAILING_WAGE',
            'PW_UNIT_OF_PAY',
            'PW_WAGE_SOURCE',
            'PW_SOURCE_YEAR',
            'PW_SOURCE_OTHER',
            'WAGE_RATE_OF_PAY_FROM',
            'WAGE_RATE_OF_PAY_TO',
            'WAGE_UNIT_OF_PAY',
            'H-1B_DEPENDENT',
            'WILLFUL_VIOLATOR',
            'WORKSITE_CITY',
            'WORKSITE_COUNTY',
            'WORKSITE_STATE',
            'WORKSITE_POSTAL_CODE',
            'ORIGINAL_CERT_DATE'
          ];
        case '2017':
          return [
            'CASE_NUMBER',
            'CASE_STATUS',
            'CASE_SUBMITTED',
            'DECISION_DATE',
            'VISA_CLASS',
            'EMPLOYMENT_START_DATE',
            'EMPLOYMENT_END_DATE',
            'EMPLOYER_NAME',
            'EMPLOYER_BUSINESS_DBA',
            'EMPLOYER_ADDRESS',
            'EMPLOYER_CITY',
            'EMPLOYER_STATE',
            'EMPLOYER_POSTAL_CODE',
            'EMPLOYER_COUNTRY',
            'EMPLOYER_PROVINCE',
            'EMPLOYER_PHONE',
            'EMPLOYER_PHONE_EXT',
            'AGENT_REPRESENTING_EMPLOYER',
            'AGENT_ATTORNEY_NAME',
            'AGENT_ATTORNEY_CITY',
            'AGENT_ATTORNEY_STATE',
            'JOB_TITLE',
            'SOC_CODE',
            'SOC_NAME',
            'NAICS_CODE',
            'TOTAL_WORKERS',
            'NEW_EMPLOYMENT',
            'CONTINUED_EMPLOYMENT',
            'CHANGE_PREVIOUS_EMPLOYMENT',
            'NEW_CONCURRENT_EMPLOYMENT',
            'CHANGE_EMPLOYER',
            'AMENDED_PETITION',
            'FULL_TIME_POSITION',
            'PREVAILING_WAGE',
            'PW_UNIT_OF_PAY',
            'PW_WAGE_LEVEL',
            'PW_SOURCE',
            'PW_SOURCE_YEAR',
            'PW_SOURCE_OTHER',
            'WAGE_RATE_OF_PAY_FROM',
            'WAGE_RATE_OF_PAY_TO',
            'WAGE_UNIT_OF_PAY',
            'H1B_DEPENDENT',
            'WILLFUL_VIOLATOR',
            'SUPPORT_H1B',
            'LABOR_CON_AGREE',
            'PUBLIC_DISCLOSURE_LOCATION',
            'WORKSITE_CITY',
            'WORKSITE_COUNTY',
            'WORKSITE_STATE',
            'WORKSITE_POSTAL_CODE',
            'ORIGINAL_CERT_DATE'
          ];
        case '2018':
          return [
            'CASE_NUMBER',
            'CASE_STATUS',
            'CASE_SUBMITTED',
            'DECISION_DATE',
            'VISA_CLASS',
            'EMPLOYMENT_START_DATE',
            'EMPLOYMENT_END_DATE',
            'EMPLOYER_NAME',
            'EMPLOYER_BUSINESS_DBA',
            'EMPLOYER_ADDRESS',
            'EMPLOYER_CITY',
            'EMPLOYER_STATE',
            'EMPLOYER_POSTAL_CODE',
            'EMPLOYER_COUNTRY',
            'EMPLOYER_PROVINCE',
            'EMPLOYER_PHONE',
            'EMPLOYER_PHONE_EXT',
            'AGENT_REPRESENTING_EMPLOYER',
            'AGENT_ATTORNEY_NAME',
            'AGENT_ATTORNEY_CITY',
            'AGENT_ATTORNEY_STATE',
            'JOB_TITLE',
            'SOC_CODE',
            'SOC_NAME',
            'NAICS_CODE',
            'TOTAL_WORKERS',
            'NEW_EMPLOYMENT',
            'CONTINUED_EMPLOYMENT',
            'CHANGE_PREVIOUS_EMPLOYMENT',
            'NEW_CONCURRENT_EMP',
            'CHANGE_EMPLOYER',
            'AMENDED_PETITION',
            'FULL_TIME_POSITION',
            'PREVAILING_WAGE',
            'PW_UNIT_OF_PAY',
            'PW_WAGE_LEVEL',
            'PW_SOURCE',
            'PW_SOURCE_YEAR',
            'PW_SOURCE_OTHER',
            'WAGE_RATE_OF_PAY_FROM',
            'WAGE_RATE_OF_PAY_TO',
            'WAGE_UNIT_OF_PAY',
            'H1B_DEPENDENT',
            'WILLFUL_VIOLATOR',
            'SUPPORT_H1B',
            'LABOR_CON_AGREE',
            'PUBLIC_DISCLOSURE_LOCATION',
            'WORKSITE_CITY',
            'WORKSITE_COUNTY',
            'WORKSITE_STATE',
            'WORKSITE_POSTAL_CODE',
            'ORIGINAL_CERT_DATE'
          ];
        case '2014-p':
          return [
            'LCA_CASE_NUMBER',
            'STATUS',
            'LCA_CASE_SUBMIT',
            'DECISION_DATE',
            'VISA_CLASS',
            'LCA_CASE_EMPLOYMENT_START_DATE',
            'LCA_CASE_EMPLOYMENT_END_DATE',
            'LCA_CASE_EMPLOYER_NAME',
            'LCA_CASE_EMPLOYER_ADDRESS',
            'LCA_CASE_EMPLOYER_CITY',
            'LCA_CASE_EMPLOYER_STATE',
            'LCA_CASE_EMPLOYER_POSTAL_CODE',
            'LCA_CASE_SOC_CODE',
            'LCA_CASE_SOC_NAME',
            'LCA_CASE_JOB_TITLE',
            'LCA_CASE_WAGE_RATE_FROM',
            'LCA_CASE_WAGE_RATE_TO',
            'LCA_CASE_WAGE_RATE_UNIT',
            'FULL_TIME_POS',
            'TOTAL_WORKERS',
            'LCA_CASE_WORKLOC1_CITY',
            'LCA_CASE_WORKLOC1_STATE',
            'PW_1',
            'PW_UNIT_1',
            'PW_SOURCE_1',
            'OTHER_WAGE_SOURCE_1',
            'YR_SOURCE_PUB_1',
            'LCA_CASE_WORKLOC2_CITY',
            'LCA_CASE_WORKLOC2_STATE',
            'PW_2',
            'PW_UNIT_2',
            'PW_SOURCE_2',
            'OTHER_WAGE_SOURCE_2',
            'YR_SOURCE_PUB_2',
            'LCA_CASE_NAICS_CODE'
          ];
      }
    }
  },
  test: {
    h1bData: function h1bData(year) {
      const dir = 'data';
      return path.join(dir, `h1b-${year}.xlsx`);
    },
    h1bDataHeaders: function h1bDataHeaders(year) {
      const toStr = new String(year);

      switch (toStr) {
        case '2014':
          return [
            'LCA_CASE_NUMBER',
            'STATUS',
            'LCA_CASE_SUBMIT',
            'DECISION_DATE',
            'VISA_CLASS',
            'LCA_CASE_EMPLOYMENT_START_DATE',
            'LCA_CASE_EMPLOYMENT_END_DATE',
            'LCA_CASE_EMPLOYER_NAME',
            'LCA_CASE_EMPLOYER_ADDRESS',
            'LCA_CASE_EMPLOYER_CITY',
            'LCA_CASE_EMPLOYER_STATE',
            'LCA_CASE_EMPLOYER_POSTAL_CODE',
            'LCA_CASE_SOC_CODE',
            'LCA_CASE_SOC_NAME',
            'LCA_CASE_JOB_TITLE',
            'LCA_CASE_WAGE_RATE_FROM',
            'LCA_CASE_WAGE_RATE_TO',
            'LCA_CASE_WAGE_RATE_UNIT',
            'FULL_TIME_POS',
            'TOTAL_WORKERS',
            'LCA_CASE_WORKLOC1_CITY',
            'LCA_CASE_WORKLOC1_STATE',
            'PW_1',
            'PW_UNIT_1',
            'PW_SOURCE_1',
            'OTHER_WAGE_SOURCE_1',
            'YR_SOURCE_PUB_1',
            'LCA_CASE_WORKLOC2_CITY',
            'LCA_CASE_WORKLOC2_STATE',
            'PW_2',
            'PW_UNIT_2',
            'PW_SOURCE_2',
            'OTHER_WAGE_SOURCE_2',
            'YR_SOURCE_PUB_2',
            'LCA_CASE_NAICS_CODE'
          ];
        case '2015':
          return [
            'CASE_NUMBER',
            'CASE_STATUS',
            'CASE_SUBMITTED',
            'DECISION_DATE',
            'VISA_CLASS',
            'EMPLOYMENT_START_DATE',
            'EMPLOYMENT_END_DATE',
            'EMPLOYER_NAME',
            'EMPLOYER_ADDRESS1',
            'EMPLOYER_ADDRESS2',
            'EMPLOYER_CITY',
            'EMPLOYER_STATE',
            'EMPLOYER_POSTAL_CODE',
            'EMPLOYER_COUNTRY',
            'EMPLOYER_PROVINCE',
            'EMPLOYER_PHONE',
            'EMPLOYER_PHONE_EXT',
            'AGENT_ATTORNEY_NAME',
            'AGENT_ATTORNEY_CITY',
            'AGENT_ATTORNEY_STATE',
            'JOB_TITLE',
            'SOC_CODE',
            'SOC_NAME',
            'NAIC_CODE',
            'TOTAL WORKERS',
            'FULL_TIME_POSITION',
            'PREVAILING_WAGE',
            'PW_UNIT_OF_PAY',
            'PW_WAGE_LEVEL',
            'PW_WAGE_SOURCE',
            'PW_WAGE_SOURCE_YEAR',
            'PW_WAGE_SOURCE_OTHER',
            'WAGE_RATE_OF_PAY',
            'WAGE_UNIT_OF_PAY',
            'H-1B_DEPENDENT',
            'WILLFUL VIOLATOR',
            'WORKSITE_CITY',
            'WORKSITE_COUNTY',
            'WORKSITE_STATE',
            'WORKSITE_POSTAL_CODE'
          ];
        case '2016':
          return [
            'CASE_NUMBER',
            'CASE_STATUS',
            'CASE_SUBMITTED',
            'DECISION_DATE',
            'VISA_CLASS',
            'EMPLOYMENT_START_DATE',
            'EMPLOYMENT_END_DATE',
            'EMPLOYER_NAME',
            'EMPLOYER_ADDRESS',
            'EMPLOYER_CITY',
            'EMPLOYER_STATE',
            'EMPLOYER_POSTAL_CODE',
            'EMPLOYER_COUNTRY',
            'EMPLOYER_PROVINCE',
            'EMPLOYER_PHONE',
            'EMPLOYER_PHONE_EXT',
            'AGENT_ATTORNEY_NAME',
            'AGENT_ATTORNEY_CITY',
            'AGENT_ATTORNEY_STATE',
            'JOB_TITLE',
            'SOC_CODE',
            'SOC_NAME',
            'NAIC_CODE',
            'TOTAL_WORKERS',
            'FULL_TIME_POSITION',
            'PREVAILING_WAGE',
            'PW_UNIT_OF_PAY',
            'PW_WAGE_SOURCE',
            'PW_SOURCE_YEAR',
            'PW_SOURCE_OTHER',
            'WAGE_RATE_OF_PAY_FROM',
            'WAGE_RATE_OF_PAY_TO',
            'WAGE_UNIT_OF_PAY',
            'H-1B_DEPENDENT',
            'WILLFUL_VIOLATOR',
            'WORKSITE_CITY',
            'WORKSITE_COUNTY',
            'WORKSITE_STATE',
            'WORKSITE_POSTAL_CODE',
            'ORIGINAL_CERT_DATE'
          ];
        case '2017':
          return [
            'CASE_NUMBER',
            'CASE_STATUS',
            'CASE_SUBMITTED',
            'DECISION_DATE',
            'VISA_CLASS',
            'EMPLOYMENT_START_DATE',
            'EMPLOYMENT_END_DATE',
            'EMPLOYER_NAME',
            'EMPLOYER_BUSINESS_DBA',
            'EMPLOYER_ADDRESS',
            'EMPLOYER_CITY',
            'EMPLOYER_STATE',
            'EMPLOYER_POSTAL_CODE',
            'EMPLOYER_COUNTRY',
            'EMPLOYER_PROVINCE',
            'EMPLOYER_PHONE',
            'EMPLOYER_PHONE_EXT',
            'AGENT_REPRESENTING_EMPLOYER',
            'AGENT_ATTORNEY_NAME',
            'AGENT_ATTORNEY_CITY',
            'AGENT_ATTORNEY_STATE',
            'JOB_TITLE',
            'SOC_CODE',
            'SOC_NAME',
            'NAICS_CODE',
            'TOTAL_WORKERS',
            'NEW_EMPLOYMENT',
            'CONTINUED_EMPLOYMENT',
            'CHANGE_PREVIOUS_EMPLOYMENT',
            'NEW_CONCURRENT_EMPLOYMENT',
            'CHANGE_EMPLOYER',
            'AMENDED_PETITION',
            'FULL_TIME_POSITION',
            'PREVAILING_WAGE',
            'PW_UNIT_OF_PAY',
            'PW_WAGE_LEVEL',
            'PW_SOURCE',
            'PW_SOURCE_YEAR',
            'PW_SOURCE_OTHER',
            'WAGE_RATE_OF_PAY_FROM',
            'WAGE_RATE_OF_PAY_TO',
            'WAGE_UNIT_OF_PAY',
            'H1B_DEPENDENT',
            'WILLFUL_VIOLATOR',
            'SUPPORT_H1B',
            'LABOR_CON_AGREE',
            'PUBLIC_DISCLOSURE_LOCATION',
            'WORKSITE_CITY',
            'WORKSITE_COUNTY',
            'WORKSITE_STATE',
            'WORKSITE_POSTAL_CODE',
            'ORIGINAL_CERT_DATE'
          ];
        case '2018':
          return [
            'CASE_NUMBER',
            'CASE_STATUS',
            'CASE_SUBMITTED',
            'DECISION_DATE',
            'VISA_CLASS',
            'EMPLOYMENT_START_DATE',
            'EMPLOYMENT_END_DATE',
            'EMPLOYER_NAME',
            'EMPLOYER_BUSINESS_DBA',
            'EMPLOYER_ADDRESS',
            'EMPLOYER_CITY',
            'EMPLOYER_STATE',
            'EMPLOYER_POSTAL_CODE',
            'EMPLOYER_COUNTRY',
            'EMPLOYER_PROVINCE',
            'EMPLOYER_PHONE',
            'EMPLOYER_PHONE_EXT',
            'AGENT_REPRESENTING_EMPLOYER',
            'AGENT_ATTORNEY_NAME',
            'AGENT_ATTORNEY_CITY',
            'AGENT_ATTORNEY_STATE',
            'JOB_TITLE',
            'SOC_CODE',
            'SOC_NAME',
            'NAICS_CODE',
            'TOTAL_WORKERS',
            'NEW_EMPLOYMENT',
            'CONTINUED_EMPLOYMENT',
            'CHANGE_PREVIOUS_EMPLOYMENT',
            'NEW_CONCURRENT_EMP',
            'CHANGE_EMPLOYER',
            'AMENDED_PETITION',
            'FULL_TIME_POSITION',
            'PREVAILING_WAGE',
            'PW_UNIT_OF_PAY',
            'PW_WAGE_LEVEL',
            'PW_SOURCE',
            'PW_SOURCE_YEAR',
            'PW_SOURCE_OTHER',
            'WAGE_RATE_OF_PAY_FROM',
            'WAGE_RATE_OF_PAY_TO',
            'WAGE_UNIT_OF_PAY',
            'H1B_DEPENDENT',
            'WILLFUL_VIOLATOR',
            'SUPPORT_H1B',
            'LABOR_CON_AGREE',
            'PUBLIC_DISCLOSURE_LOCATION',
            'WORKSITE_CITY',
            'WORKSITE_COUNTY',
            'WORKSITE_STATE',
            'WORKSITE_POSTAL_CODE',
            'ORIGINAL_CERT_DATE'
          ];
        case '2014-p':
          return [
            'LCA_CASE_NUMBER',
            'STATUS',
            'LCA_CASE_SUBMIT',
            'DECISION_DATE',
            'VISA_CLASS',
            'LCA_CASE_EMPLOYMENT_START_DATE',
            'LCA_CASE_EMPLOYMENT_END_DATE',
            'LCA_CASE_EMPLOYER_NAME',
            'LCA_CASE_EMPLOYER_ADDRESS',
            'LCA_CASE_EMPLOYER_CITY',
            'LCA_CASE_EMPLOYER_STATE',
            'LCA_CASE_EMPLOYER_POSTAL_CODE',
            'LCA_CASE_SOC_CODE',
            'LCA_CASE_SOC_NAME',
            'LCA_CASE_JOB_TITLE',
            'LCA_CASE_WAGE_RATE_FROM',
            'LCA_CASE_WAGE_RATE_TO',
            'LCA_CASE_WAGE_RATE_UNIT',
            'FULL_TIME_POS',
            'TOTAL_WORKERS',
            'LCA_CASE_WORKLOC1_CITY',
            'LCA_CASE_WORKLOC1_STATE',
            'PW_1',
            'PW_UNIT_1',
            'PW_SOURCE_1',
            'OTHER_WAGE_SOURCE_1',
            'YR_SOURCE_PUB_1',
            'LCA_CASE_WORKLOC2_CITY',
            'LCA_CASE_WORKLOC2_STATE',
            'PW_2',
            'PW_UNIT_2',
            'PW_SOURCE_2',
            'OTHER_WAGE_SOURCE_2',
            'YR_SOURCE_PUB_2',
            'LCA_CASE_NAICS_CODE'
          ];
      }
    }
  }
};

module.exports = obj[process.env.NODE_ENV];
