truncate h1b2017s;

insert into h1b2017s (
id, case_number, case_status, case_submitted, decision_date,
visa_class, employment_start_date, employment_end_date, employer_name,
employer_business_dba, employer_address, employer_city, employer_state,
employer_postal_code, employer_country, employer_province, employer_phone,
employer_phone_ext, agent_representing_employer, agent_attorney_name, agent_attorney_city,
agent_attorney_state, job_title, soc_code, soc_name, total_workers,
new_employment, continued_employment, change_previous_employment,
new_concurrent_employment, change_employer, amended_petition,
full_time_position, prevailing_wage, pw_unit_of_pay,
pw_wage_level, pw_source, pw_source_year, pw_source_other,
wage_rate_of_pay_from, wage_rate_of_pay_to, wage_unit_of_pay,
h1b_dependent, willful_violator, support_h1b, labor_con_agree,
public_disclosure_location,
worksite_city, worksite_county, worksite_state, worksite_postal_code,
original_cert_date
)
SELECT
id as id,
data->>'case_number' AS case_number,
data->>'case_status' AS case_status,
NULLIF(data->>'case_submitted', '')::timestamp AT time zone 'UTC' AS case_submitted,
NULLIF(data->>'decision_date', '')::timestamp AT time zone 'UTC' AS decision_date,
data->>'visa_class' AS visa_class,
NULLIF(data->>'employment_start_date', '')::timestamp AT time zone 'UTC' AS employment_start_date,
NULLIF(data->>'employment_end_date', '')::timestamp AT time zone 'UTC' AS employment_end_date,
data->>'employer_name' AS employer_name,
data->>'employer_business_dba' AS employer_business_dba,
data->>'employer_address' AS employer_address,
data->>'employer_city' AS employer_city,
data->>'employer_state' AS employer_state,
data->>'employer_postal_code' AS employer_postal_code,
data->>'employer_country' AS employer_country,
data->>'employer_province' AS employer_province,
NULLIF(data->>'employer_phone', '')::bigint AS employer_phone,
NULLIF(data->>'employer_phone_ext', '')::int AS employer_phone_ext,
data->>'agent_representing_employer' AS agent_representing_employer,
data->>'agent_attorney_name' AS agent_attorney_name,
data->>'agent_attorney_city' AS agent_attorney_city,
data->>'agent_attorney_state' AS agent_attorney_state,
data->>'job_title' AS job_title,
data->>'soc_code' AS soc_code,
data->>'soc_name' AS soc_name,
NULLIF(data->>'total_workers', '')::int AS total_workers,
NULLIF(data->>'new_employment', '')::int AS new_employment,
NULLIF(data->>'continued_employment', '')::int AS continued_employment,
NULLIF(data->>'change_previous_employment', '')::int AS change_previous_employment,
NULLIF(data->>'new_concurrent_employment', '')::int AS new_concurrent_employment,
NULLIF(data->>'change_employer', '')::int AS change_employer,
NULLIF(data->>'amended_petition', '')::int AS amended_petition,
data->>'full_time_position' AS full_time_position,
NULLIF(data->>'prevailing_wage', '')::bigint AS prevailing_wage,
data->>'pw_unit_of_pay' AS pw_unit_of_pay,
data->>'pw_wage_level' AS pw_wage_level,
data->>'pw_source' AS pw_source,
NULLIF(data->>'pw_source_year', '')::int AS pw_source_year,
data->>'pw_source_other' AS pw_source_other,
NULLIF(data->>'wage_rate_of_pay_from', '')::bigint AS wage_rate_of_pay_from,
NULLIF(data->>'wage_rate_of_pay_to', '')::bigint AS wage_rate_of_pay_to,
data->>'wage_unit_of_pay' AS wage_unit_of_pay,
data->>'h1b_dependent' AS h1b_dependent,
data->>'willful_violator' AS willful_violator,
data->>'support_h1b' AS support_h1b,
data->>'labor_con_agree' AS labor_con_agree,
data->>'public_disclosure_location' AS public_disclosure_location,
data->>'worksite_city' AS worksite_city,
data->>'worksite_county' AS worksite_county,
data->>'worksite_state' AS worksite_state,
data->>'worksite_postal_code' AS worksite_postal_code,
NULLIF(data->>'original_cert_date', '')::timestamp AT time zone 'UTC' AS original_cert_date
FROM temp_table_2017s;