truncate h1b2016s;

insert into h1b2016s (id, case_number, case_status, case_submitted,
decision_date, visa_class, employment_start_date, employment_end_date,
employer_name,  employer_address, employer_city, employer_state,
employer_postal_code, employer_country, employer_province, employer_phone,
employer_phone_ext, agent_attorney_name, agent_attorney_city,
agent_attorney_state, job_title, soc_code, soc_name, naic_code, total_workers,
full_time_position, prevailing_wage, pw_unit_of_pay, pw_wage_source,
pw_source_year, pw_source_other, wage_rate_of_pay_from, wage_rate_of_pay_to,
wage_unit_of_pay, h1b_dependent, willful_violator, worksite_city,
worksite_county, worksite_state, worksite_postal_code, original_cert_date)
SELECT
id as id,
data->>'case_number' AS case_number,
data->>'case_status' AS case_status,
NULLIF(data->>'case_submitted', '')::timestamp AT time zone 'UTC' AS case_submitted,
NULLIF(data->>'decision_date', '')::timestamp AT time zone 'UTC' AS decision_date,
data->>'visa_class' AS visa_class,
NULLIF(data->>'employment_start_date', '')::timestamp AT time zone 'UTC' AS employment_start_date,
NULLIF(data->>'employment_end_date', '')::timestamp AT time zone 'UTC' AS employment_end_date,
data->>'employer_name' AS employer_name,
data->>'employer_address' AS employer_address,
data->>'employer_city' AS employer_city,
data->>'employer_state' AS employer_state,
data->>'employer_postal_code' AS employer_postal_code,
data->>'employer_country' AS employer_country,
data->>'employer_province' AS employer_province,
NULLIF(data->>'employer_phone', '')::bigint AS employer_phone,
NULLIF(data->>'employer_phone_ext', '')::int AS employer_phone_ext,
data->>'agent_attorney_name' AS agent_attorney_name,
data->>'agent_attorney_city' AS agent_attorney_city,
data->>'agent_attorney_state' AS agent_attorney_state,
data->>'job_title' AS job_title,
data->>'soc_code' AS soc_code,
data->>'soc_name' AS soc_name,
NULLIF(data->>'naic_code', '')::int AS naic_code,
NULLIF(data->>'total_workers', '')::int AS total_workers,
data->>'full_time_position' AS full_time_position,
NULLIF(data->>'prevailing_wage', '')::bigint AS prevailing_wage,
data->>'pw_unit_of_pay' AS pw_unit_of_pay,
data->>'pw_wage_source' AS pw_wage_source,
NULLIF(data->>'pw_source_year', '')::int AS pw_source_year,
data->>'pw_source_other' AS pw_source_other,
NULLIF(data->>'wage_rate_of_pay_from', '')::bigint AS wage_rate_of_pay_from,
NULLIF(data->>'wage_rate_of_pay_to', '')::bigint AS wage_rate_of_pay_to,
data->>'wage_unit_of_pay' AS wage_unit_of_pay,
data->>'h1b_dependent' AS h1b_dependent,
data->>'willful_violator' AS willful_violator,
data->>'worksite_city' AS worksite_city,
data->>'worksite_county' AS worksite_county,
data->>'worksite_state' AS worksite_state,
data->>'worksite_postal_code' AS worksite_postal_code,
NULLIF(data->>'original_cert_date', '')::timestamp AT time zone 'UTC' AS original_cert_date
FROM temp_table_2016s;